### ISSUE TITLE
Add switch for pointing to config file

### ISSUE THREAD

**Issue by deadcyclo** [klimeryk/recalendar#10]
Would it be possible to add a switch for pointing to a different config file. Something like `php generate.php -c <file>`. This would be really handy for those of us who maintain several calendards. (In my instance a personal calendar and a work calendar). Most sensible I think would be for the switch to override using local config, so if the switch is present, use that file, if not look for local.config.php.

**Comment by klimeryk** [comment]
Thanks - that's a great suggestion! I've needed this myself and did not think of fixing it this way. Shows how sometimes taking a step back or a fresh perspective can be very beneficial. Thanks again - fixed in https://github.com/klimeryk/recalendar/commit/224e64db0f43ef29489237eb7bc2e543bd630611 🎉
