### ISSUE TITLE
Is it possible to remove the weekly retrospective page?

### ISSUE THREAD

**Issue by jeepitou** [klimeryk/recalendar#14]
?

**Comment by ibahson** [comment]
In the recalendar.php file you could comment ´//´out the line which generates the week-retrospective page. I'm not a skilled programmer so still trying to understand this intricate and for me awesome program. Although I´ve been able to remove the week retrospective, still not able to remove the ´R´ from the mini month calendar. Work-in-progress. 

Try doing this is the ´recalendar.php´-file: 
// $this->generate_week_retrospective( $week );

**Comment by jeepitou** [comment]
Awesome thanks! I will try to remove the R tonight when I get on my computer. I didn't think of just looking at the other files than the config xD

**Comment by jeepitou** [comment]
So to remove the R from mini month calendar, you need to modify calendar-generator.php

Comment line 46
<th scope="col" class="calendar__week-retrospective"><span>Re</span></th>

Comment line 63
//$week_overview_anchor = self::get_week_overview_anchor( $week );

Modify line 64 like below
echo "<td class=\"calendar__week-number\">$week_number</a></td>";

Comment line 97-98
//$week_retrospective_anchor = self::get_week_retrospective_anchor( $week );
//echo "<td class=\"calendar__week-retrospective\"><a href=\"#$week_retrospective_anchor\">R</a></td>";

**Comment by klimeryk** [comment]
Like mentioned above, it is technically possible, but  there's no easy to toggle option for that. Basically have to remove/comment out parts of code - should not be much, though.
