### ISSUE TITLE
Language translation to other

### ISSUE THREAD

**Issue by aaversatile** [klimeryk/recalendar#16]
Hello,

I'm trying to change language to mine but with setup to cs_CZ.UTF-8 or any other lang have no effect to day names and other texts. Months defined by me under  self::MONTHS =>... are only changed. Default languege keeps english and no idea where can I change it.

Can you help me what could be wrong? I'm generating on windows.

Thank you.

EDIT:
I really don't know, but it starts working after I changed some core files of composer... When I reverted the changes back, it still worked..., No idea what happend...

**Comment by klimeryk** [comment]
Hi, @ONYX4407, could you share your configuration file and any modifications to the library that you've made? Also, your OS and PHP versions would help 🙏

**Comment by aaversatile** [comment]
Hi, changes I've finally did are in local.config only.
Setup:
Windows10
PHP v7.4.25 (under xampp). 
your package :)

My steps:
- Installed composer from https://getcomposer.org/download 
- Install vendor from your package.
- After compiling PDF I didn't obtain translate... 
- I tried change core files of composer - some var to language config.
- After compiling PDF, translation was corect.
- I recopy all original files + composer reinstal, every PDF compiling works OK.

I can't think of any reasonable explanation. I am not sure thats usefull info..

That behave was strange, and looks like some kind of "cache" problem...

**Comment by tenJirka** [comment]
Hi. 
For me, the problem was, that cs_CZ.UTF-8 is not the installed locale. The corect form is cs_CZ.utf8

**Comment by klimeryk** [comment]
> I tried change core files of composer - some var to language config.

That feels like something that would be worth mentioning in more detail :)

But maybe check @stehji's suggestion and see if `cs_CZ.utf8` helps. If you're on Windows, you might want to check out this comment as well: https://www.reddit.com/r/RemarkableTablet/comments/odpl07/recalendar_opensource_highly_customizable/h4d1eln/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by ONYX4407** [comment]
> > I tried change core files of composer - some var to language config.
> 
> That feels like something that would be worth mentioning in more detail :)
> 
I can understand how you mean that but it was not the solution (I just remember finding vars witch operates with language)... No matter what change I did. There is finally no reason to think, the mistake is in the code. It was sth around the system, etc...

I have no idea to ultimate fix :D

**Comment by klimeryk** [comment]
Marking as resolved - please re-open if you're still having issues!
