### ISSUE TITLE
Unsupported characters

### ISSUE THREAD

**Issue by tenJirka** [klimeryk/recalendar#19]
Hello, 
I think that font used in this awsome projetct does't support czech characters like č, ř, ě and maybe more. 
It will try to change font and check if it will help.

**Comment by tenJirka** [comment]
Yeah, so changing font solved the problem.

**Comment by klimeryk** [comment]
Great, glad it was "just" a font issue. I thought Lato had good support for non-Latin characters (I'm Polish myself, so lots of ą, ż and ć ;)), but maybe not for Czech characters 🤔
