### ISSUE TITLE
Feature Request: Year overview

### ISSUE THREAD

**Issue by bennyandresen** [klimeryk/recalendar#2]
I'm quite impressed with this software! Thanks for releasing it under GPL3.

I would love if there was a single page at the start of the document that looked something like this:
![Screenshot_20210705_130301](https://user-images.githubusercontent.com/80325/124461832-6639ea00-dd91-11eb-978c-4b5724eeb7fc.png)

I would then also liked the mini-calendar on each page to have a link to that overview, like so:
![image](https://user-images.githubusercontent.com/80325/124462224-c761bd80-dd91-11eb-9308-76b0d406e411.png)

The use case is that if I'm in July and I want to add something to a different month that is further away, I have to go "next month" "next month" several times, whereas I would rather go "index" -> "actual month." That way it's always two steps, instead of variable amount of steps.

Alternatively, if you don't want a Year Index. Maybe adding a quick select for the other months to the month overview would be neat.
In this case here July is the currently selected month
![image](https://user-images.githubusercontent.com/80325/124462741-4820b980-dd92-11eb-91fb-494e0d27c0f0.png)

and I can instantly jump into December from that bar.

**Comment by DutchJoe** [comment]
Would like to see this feature too!

**Comment by klimeryk** [comment]
Thanks for the suggestion! Honestly, not sure why I did not add it :D I definitely agree it would speed up navigation - and give a nice overview of the year. I'll try to implement it by tomorrow - it should not be hard.

**Comment by klimeryk** [comment]
Done in https://github.com/klimeryk/recalendar/commit/3e64982e76536d0b06d2c98e7a28361bd45ff0e4!

The example PDF has been updated as well, but here's a sneak peek:

<img width="591" alt="Screenshot 2021-07-06 at 13 36 33" src="https://user-images.githubusercontent.com/3392497/124611755-440f9d00-de61-11eb-8d0d-66584548c63f.png">

To get to this page, just click on the year number in the small calendar on any other page 👍 Hope this helps!

**Comment by DutchJoe** [comment]
Perfect.
Love this.
