### ISSUE TITLE
Overflow pages with date

### ISSUE THREAD

**Issue by mrhlogic** [klimeryk/recalendar#26]
Hi - first of all great callendar. thanks 
Ive uploaded my created 2022 callendar and removed what I need and dont need etc. 

One question I have though is if there is anyway of adding the date to the "overflow" page (second page on each day) I would like the title to be "DD-MM-YYYY Additional Notes" with the day hyperlinks therefore if Im on an overflow page I can jump to the next day easily. Basically I need another day page with some additonal text. Is this possible I couldnt see this in your examples and wasnt able to work it out. Are you able to help?

[ReCalendar Created V1.0.pdf](https://github.com/klimeryk/recalendar/files/7778423/ReCalendar.Created.V1.0.pdf)

thanks

**Comment by klimeryk** [comment]
Hi! Thanks for trying it out!
I understand where you're coming from - and I was on the fence how to best implement this. My thinking was:
 - The extra page is needed for some additional thoughts, notes. In my case, I wanted to write down notes from a weekly meeting.
 - To I want maximum space on the page, without repeating the header, mini-calendar, etc.
 - The first page of the day will always serve as the landing page, so it's easier to distinguish it from the "sub-pages" of the day.

As for navigating - you simply swipe left or right to get to next page. That seems the simplest and most intuitive way for me - without duplicating that in the UI. While the arrows on the first page of the day will always take you to the next/previous day (skipping extra pages if the day has it). That seems most consistent and reasonable to me. Let me know if I missed a case or something, though!

If you really want to have this, I'd recommend checking out https://github.com/klimeryk/recalendar.js/, which is the same project (also by me), but rewritten from scratch. And it's in a form of a much easier to use website: https://recalendar.me/

You could probably implement what you need by re-adding the header from the page in this block: https://github.com/klimeryk/recalendar.js/blob/657d27bce5422ffa518960fddd363334bd868ec0/src/pdf/pages/day.jsx#L147. That code is much easier to extend, so I can also imagine it should be possible to add a custom "block" that will contain the header that you can add, just like you can now add lines or itinerary items. PRs are welcome ;)
