### ISSUE TITLE
Sunday-Saturday weeks

### ISSUE THREAD

**Issue by devenv** [klimeryk/recalendar#28]
Is it possible?
As far as I understand DateTimeImmutable doesn't support weeks starting on Sunday so need to convert to IntlCalendar?

**Comment by klimeryk** [comment]
It's not a feature in this version, but have a try at https://recalendar.me/. It's a rewrite of this one, but in JavaScript and in the form of an easy to use webapp. Everything is done in browser, including PDF generation. And it properly supports Sunday as the first day of the week. I'll close this issue as I don't plan to add any new features to this version (it's harder to develop, as you've noticed).

It's, of course, open-source as well: https://github.com/klimeryk/recalendar.js/

**Comment by devenv** [comment]
Amazing work, thank you!
